[tool.poetry]
name = "recutilswrap"
version = "0.1.0"
description = ""
authors = ["tullpu <tullpu@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bash = "^0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
